# Generated by Django 6.0.1 on 2026-01-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_category_job_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
